name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dumb github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With Github ""Markdown** :sparkles:
            - Created by Nobody
          reactions: '+1'
          
